export const clientPortalContent = {
  login: {
    title: "Client Portal",
    subtitle: "Sign in to view your sessions and progress.",
  },
  setPassword: {
    title: "Create your password",
    subtitle: "Choose a password to access your Client Portal.",
  },
  dashboard: {
    title: "Client Portal",
    welcome: "Welcome back",
    nextSession: "Next session",
    previousSessions: "Previous sessions",
    packages: "Package sessions",
    progress: "Progress summary",
    noNextSession: "No upcoming sessions scheduled.",
    noPreviousSessions: "No previous sessions yet.",
    noPackages: "No active packages.",
    noProgress: "Progress tracking will appear here as your work continues.",
    bookNextSession: "Book next session",
    bookPackageSession: "Book session",
    awaitingPriorSession: "Book earlier sessions first",
    remainingSessions: "remaining",
    signOut: "Sign out",
  },
  packageBooking: {
    title: "Book a package session",
    confirm: "Confirm session",
    confirming: "Booking…",
  },
  store: {
    title: "Store",
    myPurchases: "My Purchases",
    buy: "Buy",
    watch: "Watch",
    listenWatch: "Listen / Watch",
    purchased: "Purchased",
    price: "Price",
    accessDenied: "Access denied",
    signInToContinue: "Sign in to continue",
    checkoutError: "Unable to start checkout. Please try again.",
    processing: "Processing…",
    paymentSuccessNotice:
      "Thank you — your payment was received. Your purchase will appear here shortly.",
    emptyStore: "No products are available in the Store yet.",
    emptyPurchases: "You have not purchased any digital content yet.",
    contentComingSoon: "Content access will appear here when available.",
    licensedFor: "Licensed for personal use only. Do not copy, share, distribute or resell.",
    backToPurchases: "Back to My Purchases",
    productTypes: {
      SESSION: "Session",
      VIDEO: "Video",
      MEDITATION: "Meditation",
      COURSE: "Course",
    },
  },
} as const;
